{% set version = "2025.1.0" %}

package:
  name: eo-tools
  version: {{ version }}

source:
  url: https://github.com/odhondt/eo_tools/archive/{{ version }}.tar.gz
  sha256: c5440c19764528052a93e1bd7387ed584c86c2e8b06518fd6027de54e68978cb

build:
  noarch: python
  number: 0

outputs:
  - name: eo-tools
    script: build_base.sh
    requirements:
      build:
        - python
      host:
        - python
        - setuptools
        - wheel
        - pip
      run:
        - python >=3.12,<3.13
        - pytest ==8.3.3
        - gdal ==3.9.2
        - rasterio ==1.3.11
        - pyrosar ==0.24.0
        - spatialist ==0.14.0
        - pip ==24.2
        - pystac ==1.11.0
        - pystac-client ==0.8.4
        - geopandas ==1.0.1
        - pandas ==2.2.3
        - eodag ==2.12.1
        - ipykernel ==6.29.5
        - ipywidgets ==8.1.5
        - black ==24.10.0
        - scikit-image ==0.24.0
        - ipyleaflet ==0.19.2
        - folium ==0.17.0
        - tqdm ==4.66.5
        - xmltodict ==0.14.2
        - httpx ==0.27.2
        - xarray ==2024.9.0
        - netcdf4 ==1.7.1
        - rioxarray ==0.17.0
        - numba ==0.60.0
        - dask ==2024.9.1
        - bottleneck ==1.4.1
        - websockets ==13.1
        - watchfiles ==0.24.0
        - uvloop ==0.21.0
        - python-dotenv ==1.0.1
        - httptools ==0.6.1
        - planetary-computer ==1.0.0
    test:
      imports:
        - eo_tools
        - eo_tools.S1
  - name: eo_tools
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('eo-tools', max_pin="x.x.x") }}
    test:
      imports:
        - eo_tools
        - eo_tools.S1


about:
  home: https://github.com/odhondt/eo_tools
  summary: 'A toolbox for easily searching, downloading & processing remote sensing imagery from various public sources. Includes a Sentinel-1 InSAR processor.'
  description: |
    eo-tools is a pure python toolbox that is currently able to search, download and process Sentinel-1 InSAR pairs, download and mosaic Sentinel-2 tiles and download various publicly available DEM (Digital Elevation Models). The S1 processor can compute phase, amplitude and coherence in the SAR geometry and reproject them in a geographic coordinate system. Example notebooks demonstrating the different features are located in the notebooks-cf folder of the github repository.
  license: MIT
  license_file: LICENSE
  doc_url: https://eo-tools.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - odhondt
