{% set python_min = "3.12" %}
{% set version = "2026.3.0" %}

package:
  name: eo-tools
  version: {{ version }}

source:
  url: https://github.com/odhondt/eo_tools/archive/{{ version }}.tar.gz
  sha256: ad31ed236566e8a57f4e3437c5ee411800ea653854def46fb775421acc681c3d

build:
  noarch: python
  number: 0

outputs:
  - name: eo-tools
    script: build_base.sh
    requirements:
      build:
        - python
      host:
        - python {{ python_min }}
        - setuptools
        - wheel
        - pip
      run:
        - python >={{ python_min }},<3.13
        - pyproj ==3.7.2
        - pytest ==9.0.2
        - gdal ==3.12.2
        - libgdal-jp2openjpeg ==3.12.2
        - rasterio ==1.5.0
        - pyrosar ==0.35.0
        - spatialist ==0.18.0
        - pip ==26.0.1
        - pystac ==1.14.3
        - pystac-client ==0.9.0
        - geopandas ==1.1.3
        - pandas ==2.2.3
        - eodag ==3.10.0
        - ipykernel ==7.2.0
        - ipywidgets ==8.1.8
        - black ==26.3.1
        - scikit-image ==0.26.0
        - ipyleaflet ==0.20.0
        - folium ==0.20.0
        - tqdm ==4.67.3
        - xmltodict ==1.0.4
        - httpx ==0.28.1
        - xarray ==2026.2.0
        - netcdf4 ==1.7.4
        - rioxarray ==0.22.0
        - numba ==0.64.0
        - dask ==2026.3.0
        - bottleneck ==1.6.0
        - planetary-computer ==1.0.0
    test:
      requires:
        - python {{ python_min }}
      imports:
        - eo_tools
        - eo_tools.S1
  - name: eo_tools
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('eo-tools', max_pin="x.x.x") }}
    test:
      imports:
        - eo_tools
        - eo_tools.S1


about:
  home: https://github.com/odhondt/eo_tools
  summary: 'A toolbox for easily searching, downloading & processing remote sensing imagery from various public sources. Includes a Sentinel-1 InSAR processor.'
  description: |
    eo-tools is a pure python toolbox that is currently able to search, download and process Sentinel-1 InSAR pairs, geocode and apply terrain flattening to Sentinel-1 SLC products, download and mosaic Sentinel-2 tiles and download various publicly available DEM (Digital Elevation Models). The S1 InSAR processor can compute phase, amplitude and coherence in the SAR geometry and reproject them in a geographic coordinate system. Example notebooks demonstrating the different features are located in the notebooks-cf folder of the github repository.
  license: MIT
  license_file: LICENSE
  doc_url: https://eo-tools.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - odhondt
