{% set python_min = '3.12' %}
{% set version = "2025.1.0" %}

package:
  name: eo-tools
  version: {{ version }}

source:
  url: https://github.com/odhondt/eo_tools/archive/{{ version }}-build2.tar.gz
  sha256: d8cbfe1c34457edd8645cc55dff82a46957414768bbe75a3367c27d6b4169e2c

build:
  noarch: python
  number: 2

outputs:
  - name: eo-tools
    script: build_base.sh
    requirements:
      build:
        - python
      host:
        - python {{ python_min }}
        - setuptools
        - wheel
        - pip
      run:
        - python >={{ python_min }},<3.13
        - pyproj ==3.6.1
        - pytest ==8.3.4
        - gdal ==3.10.0
        - rasterio ==1.4.3
        - pyrosar ==0.27.0
        - spatialist ==0.14.0
        - pip ==24.3.1
        - pystac ==1.11.0
        - pystac-client ==0.8.5
        - geopandas ==1.0.1
        - pandas ==2.2.3
        - eodag ==2.12.1
        - ipykernel ==6.29.5
        - ipywidgets ==8.1.5
        - black ==24.10.0
        - scikit-image ==0.25.0
        - ipyleaflet ==0.19.2
        - folium ==0.19.3
        - tqdm ==4.67.1
        - xmltodict ==0.14.2
        - httpx ==0.28.1
        - xarray ==2024.11.0
        - netcdf4 ==1.7.2
        - rioxarray ==0.17.0
        - numba ==0.60.0
        - dask ==2024.12.1
        - bottleneck ==1.4.2
        - websockets ==14.1
        - watchfiles ==1.0.3
        - uvloop ==0.21.0
        - python-dotenv ==1.0.1
        - httptools ==0.6.4
        - planetary-computer ==1.0.0
    test:
      requires:
        - python {{ python_min }}
      imports:
        - eo_tools
        - eo_tools.S1
  - name: eo_tools
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('eo-tools', max_pin="x.x.x") }}
    test:
      imports:
        - eo_tools
        - eo_tools.S1


about:
  home: https://github.com/odhondt/eo_tools
  summary: 'A toolbox for easily searching, downloading & processing remote sensing imagery from various public sources. Includes a Sentinel-1 InSAR processor.'
  description: |
    eo-tools is a pure python toolbox that is currently able to search, download and process Sentinel-1 InSAR pairs, geocode and apply terrain correction to Sentinel-1 SLC products, download and mosaic Sentinel-2 tiles and download various publicly available DEM (Digital Elevation Models). The S1 InSAR processor can compute phase, amplitude and coherence in the SAR geometry and reproject them in a geographic coordinate system. Example notebooks demonstrating the different features are located in the notebooks-cf folder of the github repository.
  license: MIT
  license_file: LICENSE
  doc_url: https://eo-tools.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - odhondt
